package com.rent_tracker_app

import android.os.Bundle                       // ✅ needed for onCreate signature
import com.facebook.react.ReactActivity
import com.facebook.react.ReactActivityDelegate
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.fabricEnabled
import com.facebook.react.defaults.DefaultReactActivityDelegate
import com.zoontek.rnbootsplash.RNBootSplash   // ✅ BootSplash import

class MainActivity : ReactActivity() {

  override fun getMainComponentName(): String = "Rent_Tracker_App"

  override fun createReactActivityDelegate(): ReactActivityDelegate =
    DefaultReactActivityDelegate(this, mainComponentName, fabricEnabled)

  // ✅ Show the native splash as soon as the Activity starts
  override fun onCreate(savedInstanceState: Bundle?) {
    RNBootSplash.init(this, R.style.BootTheme) // uses the theme generated by the CLI
    super.onCreate(savedInstanceState)         // if your template used react-native-screens, you can use super.onCreate(null)
  }
}
